---
require:
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 2.4

Layout/ClassStructure:
  Enabled: true
# doesn't recognize sorbet magic comments
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Sorbet/EnforceSignatures:
  Enabled: false
Sorbet/StrictSigil:
  Enabled: false
Sorbet/StrongSigil:
  Enabled: false
Sorbet/TrueSigil:
  Exclude:
    - spec/**/*
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/NegatedIf:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/Next:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

# Pending Cops
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
