# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_4; end
module T::CompatibilityPatches::RecorderExtensions; end
